[versions]
kotlin = "1.9.22"
gatling = "3.13.3"
avro = "1.12.0"
radarSchemas = "0.8.11"
radarCommons = "1.1.3"
radarCommonsAndroid = "1.2.5"

[libraries]
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
avro = { group = "org.apache.avro", name = "avro-tools", version.ref = "avro" }
radarSchemas = { group = "org.radarbase", name = "radar-schemas-commons", version.ref = "radarSchemas" }
radarCommons = { group = "org.radarbase", name = "radar-commons", version.ref = "radarCommons" }
radarCommonsAndroid = { group = "org.radarbase", name = "radar-commons-android", version.ref = "radarCommonsAndroid" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gatling = { id = "io.gatling.gradle", version.ref = "gatling" }